# Generated by Django 5.0.6 on 2026-06-24 22:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("initial_text", models.TextField(blank=True)),
                ("final_text", models.TextField(blank=True)),
                (
                    "assistant_action",
                    models.CharField(
                        choices=[
                            ("none", "No assistant round"),
                            ("question", "Clarifying question"),
                            ("rewrite", "Suggested rewrite"),
                        ],
                        default="none",
                        max_length=12,
                    ),
                ),
                (
                    "assistant_message",
                    models.TextField(
                        blank=True,
                        help_text="The latest assistant response shown in Condition 3.",
                    ),
                ),
                ("assistant_used_llm", models.BooleanField(default=False)),
                ("revision_count", models.PositiveIntegerField(default=0)),
                (
                    "time_on_task_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=160)),
                (
                    "edition_label",
                    models.CharField(
                        help_text="e.g. 'Saturday Edition · June 21, 2026'",
                        max_length=120,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        help_text="Editorial slant of this stimulus, e.g. 'General news', 'Technology'.",
                        max_length=80,
                    ),
                ),
                ("intro", models.TextField(blank=True)),
                ("sections", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="ActionabilityRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_llm", models.BooleanField(default=False)),
                ("target_specificity", models.PositiveSmallIntegerField()),
                ("direction_operation", models.PositiveSmallIntegerField()),
                ("collection_allocation", models.PositiveSmallIntegerField()),
                ("context_persistence", models.PositiveSmallIntegerField()),
                ("system_feasibility", models.PositiveSmallIntegerField()),
                (
                    "target_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("article", "Individual article"),
                            ("section", "Newsletter section"),
                            ("collection", "Whole newsletter collection"),
                            ("unclear", "Unclear / mixed"),
                        ],
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="study.feedbackresponse",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "condition",
                    models.IntegerField(
                        choices=[
                            (1, "Just Ask"),
                            (2, "Examples + Instructions"),
                            (3, "Interactive Feedback Assistant"),
                        ]
                    ),
                ),
                (
                    "recruitment_source",
                    models.CharField(
                        choices=[
                            ("direct", "Direct link"),
                            ("movielens", "MovieLens"),
                            ("prolific", "Prolific"),
                            ("other", "Other"),
                        ],
                        default="direct",
                        max_length=20,
                    ),
                ),
                (
                    "external_ref",
                    models.CharField(
                        blank=True,
                        help_text="Optional recruitment id, e.g. a Prolific PID passed as a query param.",
                        max_length=120,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("consented", "Consented"),
                            ("viewed", "Viewed newsletter"),
                            ("feedback", "Submitted feedback"),
                            ("survey", "Completed survey"),
                            ("completed", "Completed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("consented_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=400)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participants",
                        to="study.newsletter",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="feedbackresponse",
            name="participant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="study.participant",
            ),
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("news_reading_frequency", models.PositiveSmallIntegerField()),
                ("personalized_news_exposure", models.PositiveSmallIntegerField()),
                ("baseline_clarity_topics", models.PositiveSmallIntegerField()),
                ("baseline_clarity_describe", models.PositiveSmallIntegerField()),
                ("ease_easy", models.PositiveSmallIntegerField()),
                ("ease_low_effort", models.PositiveSmallIntegerField()),
                ("confidence_express", models.PositiveSmallIntegerField()),
                ("confidence_reflects", models.PositiveSmallIntegerField()),
                ("communicability_knows", models.PositiveSmallIntegerField()),
                ("communicability_better", models.PositiveSmallIntegerField()),
                ("persistence_general", models.PositiveSmallIntegerField()),
                ("persistence_beyond", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey",
                        to="study.participant",
                    ),
                ),
            ],
        ),
    ]
