# Generated by Django 5.0.6 on 2026-06-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackresponse",
            name="assistant_action",
            field=models.CharField(
                choices=[
                    ("none", "No assistant round"),
                    ("question", "Clarifying question"),
                    ("advice", "Short advice"),
                    ("ok", "Already actionable"),
                ],
                default="none",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="condition",
            field=models.IntegerField(
                choices=[
                    (1, "Base prompt"),
                    (2, "Base prompt + examples"),
                    (3, "Base prompt + assistant guidance"),
                ]
            ),
        ),
    ]
