# Generated by Django 5.0.6 on 2026-08-04 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0010_clean_chat_log_provenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='edition_label',
        ),
    ]
